basedir: /

# html lang
language: "en"

# main menu navigation
menu:
  welcome: welcome
  # welcome/cfp.html: call for papers
  # talks_speakers: talks
  # schedule: schedule
  sponsor: sponsor
  # scommentare per generare pagina
  # menu item for workshop
  # workshop: workshop

# workshops submenu (comment out if only one workshop: add items for multiple workshops)
# workshop_submenu:
#   workshop_1: rails and vue
#   workshop_2: sample second workshop

# welcome submenu
welcome_submenu:
  about: about
  # cfp: call for papers
  where: where
  # safety: health and safety
  scholarships: scholarships
  # delete this row to take out of the menu
  coc: code of conduct

# stylesheets loaded in the <head>
stylesheets:
  - /assets/css/global.css

# scripts loaded in the end of the body / commented out to prevent errors in compiling layout.pug
scripts:
  - /assets/js/menu.js
